services:
  server:
    image: 32666dd156b17c850353b6de/66696c652d75706c6f61646572
    ports:
      - 8000:8000
    volumes:
      - cdn_files:/app/uploads
    env_file:
    - .env

volumes:
  cdn_files:
