services:
  server:
    platform: linux/amd64
    image: adityaa72/file-uploader
    ports:
      - 5000:5000
    volumes:
      - cdn_files:/app/uploads
    env_file:
    - .env

volumes:
  cdn_files:
