services:
  server:
    image: e14d9a1f4d39261c/66696c652d75706c6f61646572
    # image: adityaa72/file-uploader
    ports:
      - 7000:7000
    volumes:
      - cdn_files:/app/uploads

volumes:
  cdn_files:
